spring:
  application: { name: view }
  profiles:
    active: dev

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html

server:
  port: 3000

error:
  message-key: errorMessage

success:
  message-key: successMessage

warning:
  message-key: warningMessage

info:
  message-key: infoMessage

header:
  refresh-key-name: Refresh

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: debug
