spring:
  application: { name: view }
  profiles:
    active: dev

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html

server:
  port: 3000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
      #,http://admin:1234@localhost:8762/eureka
  instance:
    prefer-ip-address: true

error:
  message-key: errorMessage

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: debug
