name: dev-deploy-phase
on:
  push:
    branches:
      - develop

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: upload file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SSH_IP }}
          username: ${{ secrets.DEV_SSH_ID }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          source: "target/*.jar"
          target: "~/"
          rm: false

      - name: execute shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_IP }}
          username: ${{ secrets.DEV_SSH_ID }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script_stop: true
          script: "./startup.sh 3000 view"